### ISSUE TITLE
undefined index

### ISSUE THREAD

**Issue by rst630** [Max13/TelegramSocialite#1]
ErrorException
Undefined index: last_name

```
    protected function mapUserToObject(array $user)

    {

        return (new User())->setRaw($user)->map([

            'id'        => $user['id'],

            'nickname'  => $user['username'],

            'name'      => trim($user['first_name'].' '.$user['last_name']),

            'avatar'    => $user['photo_url'],

        ]);

    }
```

**Comment by Max13** [comment]
@rst630 Thanks for your issue, i've fixed it in `v2.0.1`, can you tell me if it's ok now please?

**Comment by rst630** [comment]
```
ErrorException
Undefined index: photo_url
```

**Comment by Max13** [comment]
Dude... Why do you have an empty profile

**Comment by rst630** [comment]
Telegram can't work w/o widget? In Russia it blocked and 99% of users can't access to widget.

**Comment by rst630** [comment]
> Dude... Why do you have an empty profile

not only i can be with empty profile )

**Comment by Max13** [comment]
I fixed the missing `photo_url` in `v2.0.2`

By "widget", do you mean the popup opened? Because I'm not using the widget, only the JS

**Comment by Max13** [comment]
Also, which version of PHP are you using?

**Comment by rst630** [comment]
7.4.6

Yes popup. It's possible to do with redirect like facebook socialite doing?

**Comment by Max13** [comment]
Well, actually it's a little bit complicated because contrary to other `OAuth` providers, Telegram requires a popup because when you `accept` or `decline` the connection, their script closes the current window/popup sending a message to the parent (the origin).

Other providers will send you back to **your** callback URL, which makes it possible to redirect, then come back.

What problem are you facing with the opening of the popup?

**Comment by rst630** [comment]
no problem, only that telegram banned in Russia )))

**Comment by Max13** [comment]
As `OAuth` requires to login "via" the provider's website... There is no way (regarding the package) to avoid contacting *.telegram.org, moreover if you can't legally use the app on your computer or mobile...

Anyway, feel free to send me a PR if you find a way, thank you for trying the package. Don't hesitate to open another issue if needed
